
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcertRewind.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConcertDB
    {
        public int ID { get; set; }
        public string Artist_Name { get; set; }
        public Nullable<int> Times_Searched { get; set; }
    }
}
